### ISSUE TITLE
RAWcooked formula fails on Linux

### ISSUE THREAD

**Issue by retokromer** [MediaArea/homebrew-mediaarea#44]
FYI: the current Homebrew formula fails on:

- Ubuntu 18.04.1
- Debian 9.5
- Slackware 14.2

(I haven’t tested other distributions.) Homebrew includes now also the former Linuxbrew, which works also on Windows 10 Pro and Home. That way it should be possible to install RAWcooked via this formula on almost all current platforms.

**Comment by retokromer** [comment]
(I can delve into this, but only after the 20th March, sorry.)

**Comment by g-maxime** [comment]
I'm unable to reproduce this bug anymore. Tested on Ubuntu 18.04  and Slackware 14.02 With both fresh linuxbrew setup and an old one.

**Comment by retokromer** [comment]
>I'm unable to reproduce this bug anymore. Tested on Ubuntu 18.04 and Slackware 14.02 With both fresh linuxbrew setup and an old one.

There were a lot of changes for Linux in Brew. I will try to check again before the weekend and report back.

**Comment by retokromer** [comment]
Thank you, @g-maxime! I can confirm that now the formula works fine on Debian 9.5 and Ubuntu 18.04.1 LTS, therefore I close this issue. (I presume the errors came while merging Linuxbrew into Homebrew, as many nits needed a fix.)
