### ISSUE TITLE
add installer for dvrescue-gui

### ISSUE THREAD

**Issue by dericed** [MediaArea/homebrew-mediaarea#67]
:)

**Comment by GregGagnon** [comment]
how does this look?

`cask "dvrescue" do
  version "22.12"
#  sha256 "[what is the hash?]"

  url "https://mediaarea.net/download/binary/mediainfo-gui/#{version}/dvrescue_gui_#{version}_Mac.dmg"
  name "DV Rescue"
  desc "Capture, analyze, and package DV for archival preservation" # how does this look?
  homepage "https://mediaarea.net/DVRescue"

  livecheck do
#    url "[does a dvrescue update RSS feed exist?]"
    strategy :sparkle
  end

#  depends_on macos: ">= :[which_release]"

  app "DVRescue.app"

  zap trash: [
    # List of files to zap,
  ]
end`

**Comment by JeromeMartinez** [comment]
@GregGagnon thanks for the suggestion.
But we used the template we use a bit everywhere, which leads to [that](https://github.com/MediaArea/homebrew-mediaarea/pull/82/files).
(should have done that a long time ago...)
